kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
# Immediate volume binding mode is used to have the PVC bounded once it's been created
volumeBindingMode: Immediate
